### ISSUE TITLE
Minio-Setup Exited

### ISSUE THREAD

**Issue by RaftBr** [kubernetes-bad/metachar#3]
well, I got erro here, in the minio-setup container
![image](https://github.com/kubernetes-bad/metachar/assets/98670857/a13237e6-4312-45ee-804b-a14dd128010b)
and the MetaChar look like this when I enter
![image](https://github.com/kubernetes-bad/metachar/assets/98670857/74eb1320-906a-4240-a838-11de7ba31634)
maybe it's because I'm on windows? maybe it's because I don't know how to use docker properly? _**idk lol**_

**Comment by kubernetes-bad** [comment]
That is a perfectly fine "error". What it's trying to say is that it tried to create a new bucket, but failed because the bucket has already been created - which is good.
Same goes to policy - it is already applied.
This is a helper container to set up initial S3 stuff out of the box - it runs once on every `docker compose up` to ensure all the required policies exist and are applied. You can safely ignore that.

Regarding your `failed to fetch` error - that's a separate issue, and please see what's in your browser console (what host it's trying to reach and errors out) AND your backend container logs - there may be some errors there too.

**Comment by RaftBr** [comment]
The erro on my console it's this one
![image](https://github.com/kubernetes-bad/metachar/assets/98670857/d2aabcb0-47a4-475d-9923-af8275c0fcaf)
and on my the backend have this, and for some reason the backend keeps restarting
![image](https://github.com/kubernetes-bad/metachar/assets/98670857/a6ebc1ab-6fd6-4ea6-a454-364d527c8b95)

**Comment by kubernetes-bad** [comment]
Your backend service cannot start. Please pull the latest version, see the readme on proper installation procedure. In short - you need to edit your `.env` file in `backend` folder.

**Comment by RaftBr** [comment]
> Your backend service cannot start. Please pull the latest version, see the readme on proper installation procedure. In short - you need to edit your `.env` file in `backend` folder.

what exactly I need to edit? I don't get it

**Comment by kubernetes-bad** [comment]
Do a `git pull` in your root folder first.
Then do a `cp backend/example.env backend/.env`
Then you should be able to start the backend with your usual `docker compose up`.
The file `backend/.env` contains passwords for database and S3. The example one is configured to play nicely with the rest of the docker compose, so you'll not need to edit anything if you're using it as-is. If you're bringing your own Minio, or database - that's where you'd change the passwords to access it.

**Comment by RaftBr** [comment]
> Do a `git pull` in your root folder first. Then do a `cp backend/example.env backend/.env` Then you should be able to start the backend with your usual `docker compose up`. The file `backend/.env` contains passwords for database and S3. The example one is configured to play nicely with the rest of the docker compose, so you'll not need to edit anything if you're using it as-is. If you're bringing your own Minio, or database - that's where you'd change the passwords to access it.

The `cp backend/example.env backend/.env` it's a Linux commnad, That why I'm confused, I'm on windows, and  I don't know how I do that on the **windows**

**Comment by RaftBr** [comment]
> Do a `git pull` in your root folder first. Then do a `cp backend/example.env backend/.env` Then you should be able to start the backend with your usual `docker compose up`. The file `backend/.env` contains passwords for database and S3. The example one is configured to play nicely with the rest of the docker compose, so you'll not need to edit anything if you're using it as-is. If you're bringing your own Minio, or database - that's where you'd change the passwords to access it.

The `cp backend/example.env backend/.env` it's for linux, now I did it, I use `copy backend/example.env backend/.env`, and now it's working, thanks for the help!
